apiVersion: v1
kind: Service
metadata:
  name: {{ include "kleilobby.fullname" . }}
  labels:
    {{- include "kleilobby.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    {{- include "kleilobby.selectorLabels" . | nindent 4 }}
